<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('fullpagecache')->__('Cache Block Cleaner') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanCacheBlockhtmlObjectsUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('fullpagecache')->__('Flush Cache Blockhtml Objects') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('fullpagecache')->__('Delete all Block Objects stored in Cache')?>
        </td>
    </tr>
</table>