<?php
/**
 * Template Product Edit tab Marketplace
 *
 * PHP VERSION 7
 *
 * @category    Sinanju
 * @package     Sinanju_Marketplace
 * @author      Ronan <ronan.girault@sinanju.fr>
 * @copyright   Copyright (c) 2017 Sinanju
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @contributor Ronan <ronan.girault@sinanju.fr>,
 */
?>
<?php
    $vAllMarketplaceInfo = $this->getAllMarketplaceInfo();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('sinanju_marketplace')->__('Marketplace') ?></h4>
    </div>
    <fieldset>
        <legend><?php echo Mage::helper('sinanju_marketplace')->__('Marketplace') ?></legend>
        <table cellspacing="0" class="form-list" id="table_productmarketplace">
            <?php foreach ($vAllMarketplaceInfo as $vCode => $vMarketplaceInfo) : ?>
                <?php $vSendActive = $vMarketplaceInfo->getSendActive(); ?>
                <tr>
                    <td class="value" style="width: 25px;">
                        <input type="checkbox"
                               name="marketplace[<?php echo $vCode; ?>][send]"
                               id="marketplace[<?php echo $vCode; ?>][send]"
                               <?php if($vSendActive){ echo "checked='true'";}?>
                        />
                    </td>
                    <td class="label"><?php echo Mage::helper('catalog')->__('Send to :') ?> <?php echo ucfirst($vCode); ?></td>
                    <td class="label"><?php echo Mage::helper('catalog')->__('Minimal quantity limit:') ?></td>
                    <td class="value">
                        <input type="text" name="marketplace[<?php echo $vCode; ?>][min_qty]"
                               id="marketplace[<?php echo $vCode; ?>][min_qty]"
                               value="<?php echo ($vMarketplaceInfo->getMinQtyLimit())?$vMarketplaceInfo->getMinQtyLimit():0; ?>"
                        />
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </fieldset>
</div>